---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp-dep1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springhello
  template:
    metadata:
      labels:
        app: springhello
    spec:
      containers:
      - name: springhello
        image: ksashi/qkspringjenkinsdemo:1.0
        ports:
        - name: http-port
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springapp-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: springhello
  type: NodePort
---
