# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: student-management-system-springboot-main-service
  namespace: tanmay01
spec:
  type: NodePort
  selector:
    app: student-management-system-springboot-main
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002